name: Build Flutter Windows
on:
  # 推送到 main 分支自动构建（彻底避开手动点击报错）
  push:
    branches: [main]
  # 保留手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - run: flutter pub get
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: flutter_windows_release
          path: build/windows/x64/runner/Release
